version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
            db:
              condition: service_healthy
    environment:
      - FLASK_APP=${FLASK_APP}
      - POSTGRESQL_URL=${POSTGRESQL_URL}
#    command: [ "bash", "-c", "sleep 15 && flask db upgrade && uwsgi --ini uwsgi.ini" ]
#todo  проверку есть ли бд таблица user
    command: [ "bash", "-c", "flask db upgrade && uwsgi --ini uwsgi.ini" ]
    networks:
      - app

  db:
    # образ, используемый для контейнера
    image: postgres:14-alpine
    # переменные окружения для БД
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U worker" ]
      test: [ "CMD-SHELL", "pg_isready -d app" ]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - 5432
    networks:
      - app

networks:
  app:
    driver: bridge
